service: sajadi-serverless-flask-aws
 
plugins:
  - serverless-python-requirements
  - serverless-wsgi
 
custom:
  tableName: 'device-table-${self:provider.stage}'
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
 
provider:
  name: aws
  runtime: python3.10
  stage: stage
  region: eu-north-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - { "Fn::GetAtt": ["DeviceDynamoDBTable", "Arn" ] }
  environment:
    DEVICE_TABLE: ${self:custom.tableName}
 
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /

resources:
  Resources:
    DeviceDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}